# Generated by Django 2.0.7 on 2018-08-02 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=40)),
                ('lastname', models.CharField(max_length=40)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=150)),
                ('hire_date', models.DateField()),
                ('salary', models.FloatField()),
                ('position', models.CharField(max_length=40)),
            ],
        ),
    ]
